// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfolioCalc.Core.Data;

#nullable disable

namespace PortfolioCalc.Core.Data.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20260823111620_AddTaxBaseCurrency")]
    partial class AddTaxBaseCurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("PortfolioCalc.Core.Domain.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("PortfolioCalc.Core.Domain.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxBaseCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("PortfolioCalc.Core.Domain.CashTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FeeAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeeCurrency")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("CashTransactions");
                });

            modelBuilder.Entity("PortfolioCalc.Core.Domain.FxRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FromCurrency", "ToCurrency", "Date")
                        .IsUnique();

                    b.ToTable("FxRates");
                });

            modelBuilder.Entity("PortfolioCalc.Core.Domain.InflationRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaseCurrency", "Period")
                        .IsUnique();

                    b.ToTable("InflationRates");
                });

            modelBuilder.Entity("PortfolioCalc.Core.Domain.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecurityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SecurityId");

                    b.HasIndex("AccountId", "SecurityId")
                        .IsUnique();

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("PortfolioCalc.Core.Domain.Security", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Currency")
                        .IsUnique();

                    b.ToTable("Securities");
                });

            modelBuilder.Entity("PortfolioCalc.Core.Domain.SecurityPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("SecurityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SecurityId", "Date")
                        .IsUnique();

                    b.ToTable("SecurityPrices");
                });

            modelBuilder.Entity("PortfolioCalc.Core.Domain.SecurityTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FeeAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeeCurrency")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("SecurityTransactions");
                });

            modelBuilder.Entity("PortfolioCalc.Core.Domain.UiLayoutSetting", b =>
                {
                    b.Property<string>("ScreenKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("LayoutJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ScreenKey");

                    b.ToTable("UiLayoutSettings");
                });

            modelBuilder.Entity("PortfolioCalc.Core.Domain.VocabularyEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VocabularyType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyType", "Key")
                        .IsUnique();

                    b.ToTable("VocabularyEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "US (NYSE Arca) — no suffix",
                            Key = "ARCA",
                            Value = "",
                            VocabularyType = "ExchangeYahooSuffix"
                        },
                        new
                        {
                            Id = 2,
                            Description = "US (Nasdaq) — no suffix",
                            Key = "NASDAQ",
                            Value = "",
                            VocabularyType = "ExchangeYahooSuffix"
                        },
                        new
                        {
                            Id = 3,
                            Description = "US (NYSE) — no suffix",
                            Key = "NYSE",
                            Value = "",
                            VocabularyType = "ExchangeYahooSuffix"
                        },
                        new
                        {
                            Id = 4,
                            Description = "London Stock Exchange (ETFs)",
                            Key = "LSEETF",
                            Value = ".L",
                            VocabularyType = "ExchangeYahooSuffix"
                        },
                        new
                        {
                            Id = 5,
                            Description = "London Stock Exchange",
                            Key = "LSE",
                            Value = ".L",
                            VocabularyType = "ExchangeYahooSuffix"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Xetra / Deutsche Börse",
                            Key = "IBIS",
                            Value = ".DE",
                            VocabularyType = "ExchangeYahooSuffix"
                        });
                });

            modelBuilder.Entity("PortfolioCalc.Core.Domain.CashTransaction", b =>
                {
                    b.HasOne("PortfolioCalc.Core.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PortfolioCalc.Core.Domain.Position", b =>
                {
                    b.HasOne("PortfolioCalc.Core.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortfolioCalc.Core.Domain.Security", "Security")
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Security");
                });

            modelBuilder.Entity("PortfolioCalc.Core.Domain.SecurityPrice", b =>
                {
                    b.HasOne("PortfolioCalc.Core.Domain.Security", "Security")
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Security");
                });

            modelBuilder.Entity("PortfolioCalc.Core.Domain.SecurityTransaction", b =>
                {
                    b.HasOne("PortfolioCalc.Core.Domain.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Position");
                });
#pragma warning restore 612, 618
        }
    }
}
